export const CanvasActionsTypes = <const>{
  ADD_POINT: 'ADD_POINT',
  CLEAR_CANVAS: 'CLEAR_CANVAS',
  SET_POINT: 'SET_POINT',
  SET_CONNECTION: 'SET_CONNECTION',
  SET_POTENTIAL_POINT: 'SET_POTENTIAL_POINT',
  DROP_POTENTIAL_POINT: 'DROP_POTENTIAL_POINT',
};

export const ServiceActionsTypes = <const>{
  TOGGLE_MAKE_RECORD: 'TOGGLE_MAKE_RECORD',
  TOGGLE_CONNECTION: 'ADD_CONNECTION',
};
